env:
  node: true
  es6: true
  mocha: true
parserOptions:
  ecmaVersion: 8
globals:
  expect: true
  sinon: true
rules:
  strict: 2
  no-console: 0
  arrow-parens: 0
  no-plusplus: 0
  object-curly-newline: 0
  prefer-destructuring: 0
  no-mixed-operators: 0
plugins:
  - security
extends:
  - airbnb
  - plugin:security/recommended
